refresh_library:
  description: "Rescan/Refresh Tdarr Library"
  fields:
    library:
      name: Library
      description: "Library Name to refresh"
      required: true
      example: "Movies"
      selector:
        text:
    folderpath:
      name: Folder Path
      description: "Library Folder path e.g. /Movies (Have to include this for now)"
      example: "/Movies"
      required: true
      selector:
        text:
    mode:
      name: Scan Mode
      description: "Mode to scan (default find new files only)"
      selector:
        select:
          options:
            - scanFindNew
            - scanFresh
cancel_workers_by_node_name:
  name: Cancel Workers by Node Name
  description: Cancel all workers on a node identified by its name
  fields:
    node_name:
      name: Node Name
      description: Name of the node where workers should be cancelled
      required: true
      example: "Media Server"
      selector:
        text:
    cause:
      name: Cause
      description: Reason for cancellation
      required: false
      default: "user"
      example: "system maintenance"
      selector:
        text:
