refresh_library:
  fields:
    library:
      required: true
      example: "Movies"
      selector:
        text:
    folderpath:
      required: false
      example: "/Movies"
      selector:
        text:
    mode:
      default: "scanFindNew"
      selector:
        select:
          options:
            - scanFindNew
            - scanFresh
cancel_workers_by_node_name:
  fields:
    node_name:
      required: true
      example: "Media Server"
      selector:
        text:
    cause:
      required: false
      default: "user"
      example: "system maintenance"
      selector:
        text:
