refresh_library:
  fields:
    library:
      required: true
      example: "Movies"
      selector:
        text:
    folderpath:
      required: true
      example: "/Movies"
      selector:
        text:
    mode:
      default: "scanFindNew"
      selector:
        select:
          options:
            - scanFindNew
            - scanFresh
